### ISSUE TITLE
No dataset qualities in few oml datasets

### ISSUE THREAD

**Issue by prabhant** [openml/openml-data#39]
Error while fetching these datasets
```
>>> openml.dataset.get_dataset(202)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'openml' has no attribute 'dataset'
>>> openml.datasets.get_dataset(202)
Traceback (most recent call last):
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/datasets/functions.py", line 1113, in _get_dataset_qualities_file
    with io.open(qualities_file, encoding="utf8") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/prabhant/.cache/openml/org/openml/www/datasets/202/qualities.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/datasets/functions.py", line 438, in get_dataset
    raise e
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/datasets/functions.py", line 416, in get_dataset
    qualities_file = _get_dataset_qualities_file(did_cache_dir, dataset_id)
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/datasets/functions.py", line 1117, in _get_dataset_qualities_file
    qualities_xml = openml._api_calls._perform_api_call(url_extension, "get")
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/_api_calls.py", line 65, in _perform_api_call
    response = __read_url(url, request_method, data)
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/_api_calls.py", line 204, in __read_url
    request_method=request_method, url=url, data=data, md5_checksum=md5_checksum
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/_api_calls.py", line 235, in _send_request
    __check_response(response=response, url=url, file_elements=files)
  File "/home/prabhant/anaconda3/envs/temp/lib/python3.7/site-packages/openml/_api_calls.py", line 273, in __check_response
    raise __parse_server_exception(response, url, file_elements=file_elements)
openml.exceptions.OpenMLServerException: https://www.openml.org/api/v1/xml/data/qualities/202 returned code 362: No qualities found - None
```

**Comment by prabhant** [comment]
Currently, this error is happening with datasets:
202, 486, 495, 525, and 538

Source: OpenML student assistant team

**Comment by Diederikdv** [comment]
Other datasets that we found where this happens:
559, 563, and 565.
