### ISSUE TITLE
Error Accessing Task IDs from OpenML status code:412

### ISSUE THREAD

**Issue by annawiewer** [openml/openml-data#68]
Hello,

I'm encountering a recurring error when attempting to access certain task IDs from OpenML, specifically those that are not included in the default YAML resource examples provided in the repository. The error message is outlined below.

Could you please advise on how to resolve this? Are there specific settings or configurations required for accessing non-standard task IDs?

Thanks in advance for your help! 😊

Job local.example.10m8c.Fraud_Detection_Dataset.2.autosklearn failed with error: Unexpected server error when calling **https://api.openml.org/api_splits/get/362157/Task_362157_splits.arff. Please contact the developers!
Status code: 412**
failed to perform action generate_folds. Evaluation Engine result send to EMAIL_API_LOG account.
Traceback (most recent call last):
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/tasks/task.py", line 159, in download_split
    split = OpenMLSplit._from_arff_file(cached_split_file)
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/tasks/split.py", line 88, in _from_arff_file
    raise FileNotFoundError("Split arff %s does not exist!" % filename)
FileNotFoundError: Split arff /home/devcontainers/.cache/openml/org/openml/www/tasks/362157/datasplits.arff does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/tasks/task.py", line 142, in _download_split
    with io.open(cache_file, encoding="utf8"):
FileNotFoundError: [Errno 2] No such file or directory: '/home/devcontainers/.cache/openml/org/openml/www/tasks/362157/datasplits.arff'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/_api_calls.py", line 325, in _send_request
    __check_response(response=response, url=url, file_elements=files)
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/_api_calls.py", line 391, in __check_response
    raise __parse_server_exception(response, url, file_elements=file_elements)
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/_api_calls.py", line 406, in __parse_server_exception
    server_exception = xmltodict.parse(response.text)
  File "/home/devcontainers/.local/lib/python3.9/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devcontainers/benchmarkneubenchmarkneu/automlbenchmark/amlb/job.py", line 100, in start
    self._setup()
  File "/home/devcontainers/benchmarkneubenchmarkneu/automlbenchmark/amlb/benchmark.py", line 570, in setup
    self.load_data()
  File "/home/devcontainers/benchmarkneubenchmarkneu/automlbenchmark/amlb/benchmark.py", line 538, in load_data
    self._dataset = Benchmark.data_loader.load(DataSourceType.openml_task, task_id=self._task_def.openml_task_id, fold=self.fold)
  File "/home/devcontainers/benchmarkneubenchmarkneu/automlbenchmark/amlb/datasets/__init__.py", line 21, in load
    return self.openml_loader.load(*args, **kwargs)
  File "/home/devcontainers/benchmarkneubenchmarkneu/automlbenchmark/amlb/utils/process.py", line 744, in profiler
    return fn(*args, **kwargs)
  File "/home/devcontainers/benchmarkneubenchmarkneu/automlbenchmark/amlb/datasets/openml.py", line 60, in load
    task = oml.tasks.get_task(task_id, download_qualities=False)
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/tasks/functions.py", line 384, in get_task
    raise e
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/tasks/functions.py", line 378, in get_task
    task.download_split()
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/tasks/task.py", line 162, in download_split
    self._download_split(cached_split_file)
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/tasks/task.py", line 146, in _download_split
    openml._api_calls._download_text_file(
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/_api_calls.py", line 233, in _download_text_file
    response = __read_url(source, request_method="get", md5_checksum=md5_checksum)
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/_api_calls.py", line 295, in __read_url
    return _send_request(
  File "/home/devcontainers/.local/lib/python3.9/site-packages/openml/_api_calls.py", line 362, in _send_request
    raise OpenMLServerError(
openml.exceptions.OpenMLServerError: Unexpected server error when calling https://api.openml.org/api_splits/get/362157/Task_362157_splits.arff. Please contact the developers!
Status code: 412
failed to perform action generate_folds. Evaluation Engine result send to EMAIL_API_LOG account.

**Comment by PGijsbers** [comment]
Thanks for letting us know. I think I know what is going on, though I am not 100% sure:

 - It looks like it is an issue with the task itself. It is independent of the AutoML benchmark (based on the traceback, I assume that's what you were using).
 - It looks like the data splits are not generated by our split generator. I suspect that is because it's a _classification_ task, but the target is numeric (though, this is likely an error as it seems to be a 0/1 labeled binary classification task).
 
If possible (and if this is a correct diagnosis), the easiest solution is to re-upload the dataset without encoded class labels, making the target `nominal`, which should allow the creation of classification tasks as normal.

@joaquinvanschoren anything else that may come to mind?

**Comment by annawiewer** [comment]
@PGijsbers Thanks a lot for the quick reply. Indeed my target variable was incorrect. I have used this to convert the target column to categorical with string labels, Bad_flag is my target variable:

`data['bad_flag'] = data['bad_flag'].astype(str).astype(CategoricalDtype())`

**Comment by PGijsbers** [comment]
Great! The problem is resolved then? :)

**Comment by annawiewer** [comment]
Yes the problem is resolved thanks!
